### ISSUE TITLE
Support M1

### ISSUE THREAD

**Issue by GEverding** [JanusGraph/janusgraph-docker#107]
Hi, Is it possible to push a image with Arm Support to Dockerhub?

**Comment by FlorianHockmann** [comment]
Isn't this the same as #92? That issue is also already marked with the _help wanted_ label. So, if you want to work on this and provide a pull request, then that would of course be highly welcome. There was already a PR that tried to solve this: #105 but it unfortunately still [had some problems](https://github.com/JanusGraph/janusgraph-docker/pull/105#issuecomment-1164705346).

**Comment by FlorianHockmann** [comment]
Closed as a duplicate of #92.
