### ISSUE TITLE
Drop the `latest` Docker image tag

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph-docker#25]
Even though Docker supports `latest` as a special tag which makes it easy to pull a version, this is widely recommended against:

* https://github.com/hadolint/hadolint/wiki/DL3007

  > Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag.

* https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

  > If you are shipping Docker images to a production environment, you should just ignore the latest tag. Don’t use it. Don’t be tempted by it. It’s easy to look at it and think that your deployment script should just pull “latest” and your build process will ensure that’s valid. It takes a lot of discipline to make that work. Just version your tags. Every time.

* https://vsupalov.com/docker-latest-tag/

  > You should always be explicit about versioning, otherwise things will break

Given that a new version of JanusGraph (or any software, really) can break backwards-compatibility at any time, using `latest` is a disaster waiting to happen. Users should be specifying a specific release version of the JanusGraph Docker image and relying on the functionality and APIs provided in that image and only that image, and update to the next version (if they so choose) explicitly and deliberately.

Using `latest` will only cause issues down the line for them, so we should just remove it to avoid this becoming a much larger issue down the line.

**Comment by FlorianHockmann** [comment]
I agree that users should not just use the `latest` tag in production, but do we really want to remove it altogether? I think the `latest` tag provides some value as you can just spin up a JanusGraph instance with `docker run janusgraph/janusgraph` and you get the newest version without having to know what that version is at that point of time.
Are there other popular Docker images that don't use the `latest` tag? I think it's very common to provide that and the recommendations you quoted are addressed at users so I don't think that we should drop the `latest` tag because of that.

**Comment by mbrukman** [comment]
Fair enough, SGTM. Let's keep the `latest` tag and let's hope users will use a specific version for their production deployments.
