### ISSUE TITLE
How to change docker-compose-cql-es.yml  to use remote es server?

### ISSUE THREAD

**Issue by ChenZhaobin** [JanusGraph/janusgraph-docker#65]
Hi guys,
I only change the hostname value from dockerName to ipAddress in docker-compose-cql-es.yml , then I got the error: No such property: graph for class: Script2.
    origin:
      janusgraph.storage.hostname: jce-cassandra
      janusgraph.index.search.hostname: jce-elastic
   After Change:
      janusgraph.storage.hostname: 127.0.0.1:9042
      janusgraph.index.search.hostname: 127.0.0.1:9200

Could someone help me out please?

**Comment by FlorianHockmann** [comment]
Sorry for this really late reply, but these options really only take a hostname or an IP address or a comma-separated list of those as described [in the Configuration Reference](https://docs.janusgraph.org/configs/configuration-reference/#storage) without **a port**. I guess that was the problem here.

I'm also closing this now as it's already nearly two years old. If this problem is still a problem for you, then please ask first on one of our [community channels](https://docs.janusgraph.org/configs/configuration-reference/#storage) as it's easier to help you there and we're only using GitHub issue for concrete bug reports or feature requests.
