### ISSUE TITLE
ARM64 Image

### ISSUE THREAD

**Issue by dantestopp** [JanusGraph/janusgraph-docker#92]
I would like to run a development environment with Janusgraph, Solr and Cassandra on my Raspberry Pies. Solr and Cassandra both provide ARM64 compatible images on Docker Hub. 

Sadly Janusgraph only provides AMD images.

It would be nice if Janusgraph had also compatible images. 

Thank you for your feedback.

**Comment by FlorianHockmann** [comment]
Supporting ARM64 sounds like a good idea of course and there seems to be a lot of interest in this, considering the amount of 👍  this already got. Anyone here who is willing to provide a PR for this?

**Comment by analytically** [comment]
@FlorianHockmann this should be prioritised

**Comment by Jrb1x** [comment]
Any updates on this? I noticed 1.0RC came out but still no ARM support.

**Comment by li-boxuan** [comment]
I have made a PR. I also uploaded the images to my personal docker-hub: https://hub.docker.com/r/liboxuanhk/janusgraph/tags

**Comment by li-boxuan** [comment]
Note that the `./bin/gremlin.sh` inside the Docker image won't work for ARM machines due to the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, /tmp/libjansi-64-8999118035290383984.so: /tmp/libjansi-64-8999118035290383984.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]
```

I am not sure why this is the case, but running the server alone inside the Docker image is fine. I am able to download the zip file from https://github.com/JanusGraph/janusgraph/releases and use the local gremlin console to connect to the server. I am using openjdk version "1.8.0_275".
